2020-08-21 15:00:32.161 dev  WARN 26668 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:00:32.164 dev  WARN 26668 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:00:32.165 dev  WARN 26668 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:00:40.625 dev  WARN 26668 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:01:35.480 dev  WARN 26668 --- [RMI TCP Connection(1)-192.200.6.58] o.s.b.a.jdbc.DataSourceHealthIndicator   : DataSource health check failed

org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is com.alibaba.druid.pool.DataSourceDisableException
	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:323)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.getProduct(DataSourceHealthIndicator.java:119)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doDataSourceHealthCheck(DataSourceHealthIndicator.java:107)
	at org.springframework.boot.actuate.jdbc.DataSourceHealthIndicator.doHealthCheck(DataSourceHealthIndicator.java:102)
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
	at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:95)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:76)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:324)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.druid.pool.DataSourceDisableException: null
	at com.alibaba.druid.pool.DruidDataSource.close(DruidDataSource.java:2010)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.invokeCustomDestroyMethod(DisposableBeanAdapter.java:339)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:273)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1036)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1029)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1057)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1026)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:945)

2020-08-21 15:01:44.118 dev  WARN 9200 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:01:44.119 dev  WARN 9200 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:01:44.119 dev  WARN 9200 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:01:49.052 dev  WARN 9200 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:03:37.508 dev  WARN 26496 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:03:37.508 dev  WARN 26496 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:03:37.509 dev  WARN 26496 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:03:44.404 dev  WARN 26496 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:04:00.005 dev  WARN 26496 --- [http-nio-8989-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:04:54.736 dev  WARN 28012 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:04:54.736 dev  WARN 28012 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:04:54.737 dev  WARN 28012 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:05:00.070 dev  WARN 28012 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:05:05.436 dev  WARN 28012 --- [http-nio-8989-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:05:06.675 dev  WARN 28012 --- [http-nio-8989-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:05:51.840 dev  WARN 28012 --- [http-nio-8989-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:07:35.489 dev  WARN 27384 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:07:35.490 dev  WARN 27384 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:07:35.490 dev  WARN 27384 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:07:40.286 dev  WARN 27384 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:09:59.590 dev  WARN 26520 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:09:59.591 dev  WARN 26520 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:09:59.591 dev  WARN 26520 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:10:06.162 dev  WARN 26520 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:10:34.560 dev  WARN 23120 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:10:34.561 dev  WARN 23120 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:10:34.562 dev  WARN 23120 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:10:40.041 dev  WARN 23120 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:12:14.059 dev  WARN 23120 --- [http-nio-8989-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@432ec349]; default message [传入参数价格不能大于100]]
2020-08-21 15:12:15.988 dev  WARN 23120 --- [http-nio-8989-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@f1470d9]; default message [传入参数价格不能大于100]]
2020-08-21 15:12:25.369 dev  WARN 23120 --- [http-nio-8989-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@7e66aa7b]; default message [传入参数价格不能大于100]]
2020-08-21 15:12:30.234 dev  WARN 23120 --- [http-nio-8989-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@4ed58ffa]; default message [传入参数价格不能大于100]
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:12:31.190 dev  WARN 23120 --- [http-nio-8989-exec-9] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@1776f026]; default message [传入参数价格不能大于100]
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:12:50.626 dev  WARN 23120 --- [http-nio-8989-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:12:51.782 dev  WARN 23120 --- [http-nio-8989-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:40:42.267 dev  WARN 26900 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:40:42.268 dev  WARN 26900 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:40:42.268 dev  WARN 26900 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:40:47.364 dev  WARN 26900 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:41:01.529 dev  WARN 26900 --- [http-nio-8989-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:41:02.882 dev  WARN 26900 --- [http-nio-8989-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:41:03.635 dev  WARN 26900 --- [http-nio-8989-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:41:05.003 dev  WARN 26900 --- [http-nio-8989-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:41:08.940 dev  WARN 26900 --- [http-nio-8989-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:41:12.715 dev  WARN 26900 --- [http-nio-8989-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:41:16.920 dev  WARN 26900 --- [http-nio-8989-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@1087dce0]; default message [传入参数价格不能大于100]]
2020-08-21 15:42:12.843 dev  WARN 26900 --- [http-nio-8989-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@137b3478]; default message [传入参数价格不能大于100]]
2020-08-21 15:42:19.814 dev  WARN 26900 --- [http-nio-8989-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:42:51.211 dev  WARN 26900 --- [http-nio-8989-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:47:51.691 dev  WARN 26900 --- [http-nio-8989-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:48:13.568 dev  WARN 26900 --- [http-nio-8989-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@133aacd1]; default message [传入参数价格不能大于100]]
2020-08-21 15:48:49.203 dev  WARN 26900 --- [http-nio-8989-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:48:57.365 dev  WARN 26900 --- [http-nio-8989-exec-8] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'java.lang.Integer'; nested exception is java.lang.NumberFormatException: For input string: "is"]
2020-08-21 15:49:17.742 dev  WARN 26900 --- [http-nio-8989-exec-10] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@53635a0d]; default message [传入参数价格不能大于100]]
2020-08-21 15:50:23.508 dev  WARN 27232 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:50:23.509 dev  WARN 27232 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:50:23.509 dev  WARN 27232 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:50:29.634 dev  WARN 27232 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:50:36.912 dev  WARN 27232 --- [http-nio-8989-exec-2] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@3cf5290e]; default message [传入参数价格不能大于100]]
2020-08-21 15:50:54.005 dev  WARN 27232 --- [http-nio-8989-exec-4] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@793a7ff0]; default message [传入参数价格不能大于100]]
2020-08-21 15:51:01.544 dev  WARN 27232 --- [http-nio-8989-exec-6] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 2 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@19963be6]; default message [传入参数价格不能大于100]
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:51:23.125 dev  WARN 27232 --- [http-nio-8989-exec-7] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'id': rejected value [null]; codes [NotNull.book.id,NotNull.id,NotNull.java.lang.Integer,NotNull]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.id,id]; arguments []; default message [id]]; default message [id不能为空]]
2020-08-21 15:53:56.447 dev  WARN 27232 --- [http-nio-8989-exec-3] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.validation.BindException: org.springframework.validation.BeanPropertyBindingResult: 1 errors
Field error in object 'book' on field 'price': rejected value [300.0]; codes [DecimalMax.book.price,DecimalMax.price,DecimalMax.java.lang.Double,DecimalMax]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [book.price,price]; arguments []; default message [price],true,org.springframework.validation.beanvalidation.SpringValidatorAdapter$ResolvableAttribute@2724a805]; default message [传入参数价格不能大于100]]
2020-08-21 15:55:27.529 dev  WARN 19112 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:55:27.530 dev  WARN 19112 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:55:27.531 dev  WARN 19112 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:55:33.338 dev  WARN 19112 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:56:20.793 dev  WARN 12060 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:56:20.794 dev  WARN 12060 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:56:20.794 dev  WARN 12060 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:56:25.704 dev  WARN 12060 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
2020-08-21 15:57:05.173 dev  WARN 28500 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'personMapper' and 'com.zzu.demo.dao.PersonMapper' mapperInterface. Bean already defined with the same name!
2020-08-21 15:57:05.174 dev  WARN 28500 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : Skipping MapperFactoryBean with name 'userDao' and 'com.zzu.demo.dao.UserDao' mapperInterface. Bean already defined with the same name!
2020-08-21 15:57:05.174 dev  WARN 28500 --- [restartedMain] o.m.s.mapper.ClassPathMapperScanner      : No MyBatis mapper was found in '[com.zzu.demo.dao]' package. Please check your configuration.
2020-08-21 15:57:09.949 dev  WARN 28500 --- [restartedMain] c.b.m.core.injector.AbstractMethod       : [com.zzu.demo.dao.PersonMapper.selectById] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.SelectById]
